In [1]:
import pandas as pd
import geopandas as gpd
import matplotlib.pyplot as plt

from shapely.geometry import Point

In [2]:
print(gpd.__version__)

1.2.0

In [3]:
data = {
    "name": [
        "Charger A",
        "Charger B",
        "Charger C",
        "Charger D"
    ],
    "latitude": [
        60.3913,
        60.3775,
        60.4050,
        60.3650
    ],
    "longitude": [
        5.3221,
        5.3350,
        5.2900,
        5.3450
    ],
    "power_kw": [
        150,
        300,
        50,
        200
    ]
}

df = pd.DataFrame(data)

df

        name  latitude  longitude  power_kw
0  Charger A   60.3913     5.3221       150
1  Charger B   60.3775     5.3350       300
2  Charger C   60.4050     5.2900        50
3  Charger D   60.3650     5.3450       200

In [4]:
chargers = gpd.GeoDataFrame(
    df,
    geometry=gpd.points_from_xy(
        df["longitude"],
        df["latitude"]
    ),
    crs="EPSG:4326"
)

chargers

        name  latitude  longitude  power_kw                geometry
0  Charger A   60.3913     5.3221       150  POINT (5.3221 60.3913)
1  Charger B   60.3775     5.3350       300   POINT (5.335 60.3775)
2  Charger C   60.4050     5.2900        50     POINT (5.29 60.405)
3  Charger D   60.3650     5.3450       200    POINT (5.345 60.365)

In [5]:
type(chargers)

geopandas.geodataframe.GeoDataFrame